name: Autosort sources.json

on:
  push:
    paths:
      - 'sources.json'
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-sort:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Validate and Sort JSON
      uses: marketplaces/actions/json-utils@v1
      with:
        path-to-json: 'sources.json'
        action: 'sort'
        type: "nested-json"
        key: "name"

