name: Autosort sources.json

on:
  workflow_dispatch:
  # push:
  pull_request:
    paths:
      - 'sources.json'

jobs:
  validate-and-sort:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Configure Git User
      run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Validate and Sort JSON
      uses: yakubique/json-utils@v1.7
      id: sorted_sources
      with:
        space: 4 # indent
        action: 'sort'
        type: "nested-json"
        key: "name"
        from_file: 'true'
        to_file: 'true'
        input: 'sources.json'

    - name: Move sorted JSON
      run: |
        cp "${{ steps.sorted_sources.outputs.result }}" sources.json
        git add sources.json
        # git commit -m "Sort sources.json"
        # git push

    - name: Push sorted JSON
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Autosort sources.json"
