name: Validate JSON Schemas (dsanders11)
'on':
  workflow_dispatch: null
  push:
    paths:
      - '/sources.json'
  pull_request:
    paths:
      - '/sources.json'
permissions: read-all
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Validate sources.json
        continue-on-error: true
        uses: dsanders11/json-schema-validate-action@main
        with:
          files: sources.json
          schema: sources.schema.json