name: Validate JSON Schemas (ammarlakis)
'on':
  workflow_dispatch: null
  push:
    branches:
      - dev
permissions: read-all
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Validate sources.json
        uses: ammarlakis/action-ajv@master
        with:
          data: sources.json
          schema: sources.schema.json
          allErrors: true
          verbose: true