name: Validate changed Github workflows
'on':
  workflow_dispatch: null
  push:
    paths:
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - '.github/workflows/**.yml'
permissions: read-all
jobs:
  validate:
    name: Validate GitHub Actions workflows
    permissions:
      contents: read
      packages: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0            
      - name: Validate workflows
        continue-on-error: true
        uses: dsanders11/json-schema-validate-action@main
        with:
          schema: https://json.schemastore.org/github-workflow.json
          files: .github/workflows/**.yml
